source 'https://github.com/GetuiLaboratory/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

pod 'CocoaAsyncSocket', '~> 7.6.3'

target 'SocketDemo' do
    
end

target 'SocketDemoTests' do
    
end

target 'SocketDemoUITests' do
    
end
